### ISSUE TITLE
Summaries of breaking changes in 2.0.0?

### ISSUE THREAD

**Issue by martincarles** [emedware/vue-golden-layout#47]
Hello and thank you for your work on this library.
I see you released a new major version 2.0.0 this week, I'm looking into it.
I looked at the Changelog doc that highlights what's new but could you please specify which changes are breaking backward compatibility ?

It would make our life easier while migrating to 2.0.

Thanks !

**Comment by eddow** [comment]
Hello,
Basically, the use of templates for components. After some memory-leaks hunting, the templating system went obsolete and now all components should now be defined in-place.
If something has to be re-used, a separate Vue component should be used.

That's mainly it.

**Comment by eddow** [comment]
There is no more named slots nor `template` attributes to the component.

Namely, this part of the documentation went obsolete :

## Named templates

In order to use `v-if` and `v-for` to control the content, templates have to be defined and used with a name.
If this rule is broken :

- Popup will display blank
- Loading a saved state will fail
- This will be displayed in the console: "Dynamic golden-layout components should be named templates instead."

### Defining a template

This is done through `slot`s in the `<golden-layout>` element (the square brackets stand for "optional")

```html
<template slot="template-name"[ slot-scope="myState"]>
    ...
</template>
```

The content of `myState` can of course be changed. This will be saved/loaded when the overall state is saved/loaded.

### Using a template

`gl-component` has a `template` property. This is a string that target the `slot` defined.
It also (useful for `v-for`s) has a `state` property that will be used as the `slot-scope`

```html
<gl-component v-for="sth in swhr" :key="sth.else" template="template-name" :state="sth.state" />
```

**Comment by eddow** [comment]
The [demo](https://github.com/emedware/vue-golden-layout#bigger-example) is always up to date with the library.
