### ISSUE TITLE
not working together with vue dev tools

### ISSUE THREAD

**Issue by Kuperwood** [emedware/vue-golden-layout#59]
Hello
It seems not working together with vue dev tools. 
``` javascript
import Vue from 'vue';
import Test from './Test';
import vgl from 'vue-golden-layout'
Vue.use(vgl);
new Vue({
    render: h => h(Test),
}).$mount('#test');
```
``` html
<template>
    <div>
        <golden-layout>
            <gl-row>
                <gl-stack>
                    <gl-component :title="'Test'">
                        <h2>Test</h2>
                    </gl-component>
                </gl-stack>
            </gl-row>
        </golden-layout>
    </div>
</template>
<script>
    export default {
        name: "Test"
    }
</script>
```
When the page is loaded, after visit dev tools, then each event of golden layout (e.g drag) will give this:
![backend-no-props](https://user-images.githubusercontent.com/61699034/75690314-838d0e80-5c9a-11ea-81f3-a0871a2004e9.png)
Then it exists until the browser reopen. 
How to make it work with dev-tools?

**Comment by eddow** [comment]
Before making tests by myself, may I please ask you to try something ?
To create a component that shares only `render` seems weird to me.
How is it working when you replace :
```js
new Vue({
    render: h => h(Test),
}).$mount('#test');
```
by this:
```js
new Test({el: '#test'});
```

**Comment by Kuperwood** [comment]
thanks for your package, this is very useful!
I maked a minimum setup as attempt to reporoduce the problem
[vgl-test.zip](https://github.com/emedware/vue-golden-layout/files/4282869/vgl-test.zip)
Please, run devserver, then open a vue devtools console and then try to move golden-layout tab

**Comment by eddow** [comment]
I unfortunately cannot reproduce the bug and move the tabs with no problem .....

**Comment by Kuperwood** [comment]
it is easy to reporoduce this in other way, to use the close event
Example:
![dev-tools](https://user-images.githubusercontent.com/61699034/75909495-1d43ef80-5e44-11ea-9536-5d6eba421932.gif)

**Comment by eddow** [comment]
So, indeed, the bug occurs when one uses the `Vue` tab of dev-tools.
It comes from a hack I had to use to avoid golden-layout objects to be observed for performance reason - if they were observed by Vue, even the simple demo would freeze for minutes to open a new tab.
The hack I used was to mark g-l objects with `_isVue = true`, hence the debugger tries to treat them as Vue object.
I tried many other possibilities but unfortunately, there is no viable way to stop that observation of g-l objects. I'll perhaps again later try to make them Vue-object enough for them not to bug in dev-tools, even if the resulting structure will be wrong - or try other ways to make them unobserved if I think of any.

Note: I explained here so that if anyone having an idea is more than welcome to propose it

**Comment by VasilisNikiforidis** [comment]
The exact same happens for me too, glad to see it's not only my problem xD
Any work around?
It is a bit annoying having to reopen project in new tab every time I want to check Vue dev tools :/

**Comment by eddow** [comment]
Well, it seems that it is using the "Vue" tab in vue-dev-tools. As I have the tab but never used it, I didn't discover it.
I'm looking for time to time to find a better hack to stop the observation on the gl-objects but didn't find yet

**Comment by NeverBehave** [comment]
https://github.com/rpkilby/vue-nonreactive
I have tried this and it looks like there is no props error appears
