### ISSUE TITLE
component state error

### ISSUE THREAD

**Issue by WineHan** [emedware/vue-golden-layout#62]
Hello , I run the demo program, and I changed  code to gl-component a/b/c .
![code-snapshot](https://user-images.githubusercontent.com/57558230/76382718-925b7b80-6394-11ea-906c-819eeb1b13a3.png)

But when I deleted gl-component b and refresh browser , gl-component c will disappear instead b.
I also delete compA component but got error.

![demo](https://user-images.githubusercontent.com/57558230/76382747-abfcc300-6394-11ea-9350-080a3a383128.gif)

<img width="1208" alt="error" src="https://user-images.githubusercontent.com/57558230/76382996-6bea1000-6395-11ea-8a24-f1df26644560.png">

Is there anything wrong I'm doing here? 
Let me know if you need me to provide any more information.
Thank you for your help

**Comment by eddow** [comment]
I can reproduce the bug but not the error message - and debugging blind is a little bit tireing :">
Could you tell me when you have this error message? When you close "b"? When you reload ? At an other moment?

**Comment by eddow** [comment]
Okay, it is so unintuitive that even I needed time to understand ;-)
It comes from this line of README.md about saving;/restoring states :
> In order to reload a state, the Vue object structure must be reloaded identical too

Indeed, I'll write "identical to the reloaded state" or something like that

The problem is that you give a state with 2 columns (a and c) while you give a vue structure with 3 columns (a, b and c)

The workaround for you is th `@Preserve` an object that conatins `{a: true, b: true, c: true}`, display the column v-if his letter is at true then sets one to false when the  column gets closed.

It can sound like an overload for such a small example but these pure-textual content items are rarely used.

In the demo application, there is one pane like this, the bottom pane : and it is displayed or not by Vue not because of the golden-layout state, but because of a variable that is preserved : `demoStackState.bottomSheet`
