### ISSUE TITLE
Compiling project

### ISSUE THREAD

**Issue by NeverBehave** [emedware/vue-golden-layout#84]
Due to https://github.com/emedware/vue-golden-layout/issues/66#issuecomment-671481230, I am trying to host a fork on local machine. However, I found that the after `yarn prepack` runs, the compiled version does not working properly.

The problem is like the component `<golden-layout>` is missing from children component and so injection fails. 

Repo: https://github.com/NeverBehave/golden-layout-quasar
Steps:
- run `yarn && yarn prepack` under `deps/vue-golden-layout`
- run `yarn && yarn dev:browser` under root

The project works just fine with version on npm but failed on local compile one. How to properly compile this project?

**Comment by eddow** [comment]
Well, I usually use `npm prepack` - perhaps do yarn/npm have some differences .... ?

**Comment by heyakyra** [comment]
@eddow 

The latest [version `2.1.2` on the `npm` repository](https://www.npmjs.com/package/vue-golden-layout/v/2.1.2?activeTab=code) does not include a `dist` directory with the built package. 

Adding a `postinstall` script like:

```
  "scripts": {
    …
    "postinstall": "cd node_modules/vue-golden-layout && npm install --force && echo 'yes' | npm run prepack",
  },
```

also does not work because: 

`ERROR in Entry module not found: Error: Can't resolve './src' in '/path/to/node_modules/vue-golden-layout'`
